### ISSUE TITLE
Incompatible with latest openssl

### ISSUE THREAD

**Issue by ylecuyer** [rvm/rvm#3659]
With the latest openssl version I have the error:

```
Using /home/ylecuyer/.rvm/gems/ruby-2.2.1 with gemset project
Error loading RubyGems plugin "/home/ylecuyer/.rvm/gems/ruby-2.2.1@global/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": /home/ylecuyer/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-linux/openssl.so: undefined symbol: SSLv2_method - /home/ylecuyer/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-linux/openssl.so (LoadError)
Error loading RubyGems plugin "/home/ylecuyer/.rvm/gems/ruby-2.2.1@global/gems/gem-wrappers-1.2.7/lib/rubygems_plugin.rb": /home/ylecuyer/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-linux/openssl.so: undefined symbol: SSLv2_method - /home/ylecuyer/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-linux/openssl.so (LoadError)
```

OpenSSL version: `openssl-1.0.2.g-3-x86_64.pkg.tar.xz`

**Comment by brauliobo** [comment]
```
                           ^                                                                                                                                                                 
ossl_ssl.c:100:46: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’                                                                                                                      
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, name##_method }                                                                                                                                
                                              ^                                                                                                                                              
ossl_ssl.c:114:27: error: ‘SSLv3_server_method’ undeclared here (not in a function)                                                                                                          
     OSSL_SSL_METHOD_ENTRY(SSLv3_server),                                                                                                                                                    
                           ^                                                                                                                                                                 
ossl_ssl.c:100:46: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’                                                                                                                      
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, name##_method }                                                                                                                                
                                              ^                                                                                                                                              
ossl_ssl.c:115:27: error: ‘SSLv3_client_method’ undeclared here (not in a function)                                                                                                          
     OSSL_SSL_METHOD_ENTRY(SSLv3_client),                                                                                                                                                    
                           ^                                                                                                                                                                 
ossl_ssl.c:100:46: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’                                                                                                                      
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, name##_method }                                                                                                                                
                                              ^                                                                                                                                              
ossl_ssl.c:116:27: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]                                                                                     
     OSSL_SSL_METHOD_ENTRY(SSLv23),                                                                                                                                                          
                           ^                                                                                                                                                                 
ossl_ssl.c:100:46: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’                                                                                                                      
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, name##_method }                                                                                                                                
                                              ^                                                                                                                                              
ossl_ssl.c:116:27: note: (near initialization for ‘ossl_ssl_method_tab[6].func’)                                                                                                             
     OSSL_SSL_METHOD_ENTRY(SSLv23),                                                                                                                                                          
                           ^                                                                                                                                                                 
ossl_ssl.c:100:46: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’                                                                                                                      
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, name##_method }                                                                                                                                
                                              ^                                                                                                                                              
ossl_ssl.c:117:27: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]                                                                                     
     OSSL_SSL_METHOD_ENTRY(SSLv23_server),                                                                                                                                                   
                           ^                                                                                                                                                                 
ossl_ssl.c:100:46: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’                                                                                                                      
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, name##_method }                                                                                                                                
                                              ^                                                                                                                                              
ossl_ssl.c:117:27: note: (near initialization for ‘ossl_ssl_method_tab[7].func’)                                                                                                             
     OSSL_SSL_METHOD_ENTRY(SSLv23_server),                                                                                                                                                   
                           ^                                                                                                                                                                 
ossl_ssl.c:100:46: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’                                                                                                                      
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, name##_method }                                                                                                                                
                                              ^                                                                                                                                              
ossl_ssl.c:118:27: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]                                                                                     
     OSSL_SSL_METHOD_ENTRY(SSLv23_client),                                                                                                                                                   
```
found similar error while building ree/1.8.7

**Comment by brauliobo** [comment]
This is a good workaround: https://wiki.archlinux.org/index.php/RVM#Ruby_1.8.x_won.27t_compile_with_RVM

**Comment by codelitt** [comment]
In ArchLinux it is the same basic error but a slight difference. Also have a work around and possible solution. 

```
Error running '__rvm_make -j1',
showing last 15 lines of /home/cody/.rvm/log/1461940454_ruby-2.2.0/make.log
ossl_ssl.c:143:27: error: ‘SSLv3_client_method’ undeclared here (not in a function)
     OSSL_SSL_METHOD_ENTRY(SSLv3_client),
                           ^
ossl_ssl.c:119:69: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                     ^
Makefile:293: recipe for target 'ossl_ssl.o' failed
make[2]: *** [ossl_ssl.o] Error 1
make[2]: Leaving directory '/home/cody/.rvm/src/ruby-2.2.0/ext/openssl'
exts.mk:202: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: Leaving directory '/home/cody/.rvm/src/ruby-2.2.0'
uncommon.mk:187: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.
```

###Workaround
So basically patchlevels do not like the newer OpenSSL versions. 
`$ rvm pkg install openssl

**Comment by pkuczynski** [comment]
This has been fixed in latest master. Please switch and test: `rvm get master`

**Comment by dan-higgins** [comment]
Sorry to resurrect this but these old OpenSSL and Ruby versions just bite us over and over.

I was able to get `ruby-1.8.7-p374` to install only by doing this:
```
$ rvm pkg install openssl
$ env PKG_CONFIG_PATH=~/.rvm/usr/lib/pkgconfig optflags='-w -Wno-pedantic' \
  rvm install -C --with-openssl-dir=~/.rvm/usr 1.8.7-p374
```
This is Arch Linux with `gcc 7.1.1` installed.

HOWEVER, IT STILL WON'T RUN, giving me this error:
```
$ rvm use 1.8.7-p374
Using /home/dan/.rvm/gems/ruby-1.8.7-p374
$ gem list

*** LOCAL GEMS ***


$ gem install rubygems
ERROR:  Loading command: install (LoadError)
	/home/dan/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/x86_64-linux/openssl.so: undefined symbol: SSLv3_method - /home/dan/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/x86_64-linux/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

I wonder if previous fixes for avoiding the new OpenSSL have now also broken the linkage to the old OpenSSL. Shrug.

**Comment by ccarterc** [comment]
Tried installing ruby 2.3.1 with rvm on PopOS 18 (ubuntu 18 variant).  Got the following error:

```
linking shared-object json/ext/parser.so
ossl_x509req.c: In function ‘ossl_x509req_get_signature_algorithm’:
ossl_x509req.c:314:34: error: dereferencing pointer to incomplete type ‘X509_REQ {aka struct X509_req_st}’
     if (!i2a_ASN1_OBJECT(out, req->sig_alg->algorithm)) {
                                  ^~
compiling psych_to_ruby.c
Makefile:301: recipe for target 'ossl_x509req.o' failed
make[2]: *** [ossl_x509req.o] Error 1
make[2]: Leaving directory '/usr/share/rvm/src/ruby-2.3.1/ext/openssl'
exts.mk:209: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
compiling psych_emitter.c
```
