### ISSUE TITLE
Impossible to install Rubinius on macOS because of deleted llvm35 brew formulae

### ISSUE THREAD

**Issue by habovh** [rvm/rvm#3901]
## Description

I'm trying to install `rbx-3.7` on macOS Sierra 10.12.3, and it fails because `rvm` forces the `llvm35` dependency, which formulae has been removed from homebrew repositories (including boneyard).

Apparently, in this #3722 you decided to force the dependency to match Rubinius needs, but I think this might be outdated.

Isn't Rubinius capable of build on a more recent `llvm` version? Be it either the Mac's included llvm or a more recent homebrew formulae?

## Debug info

Console output:
```
habovh@habovh-MBP ~ $ rvm install rbx-3.7
Checking requirements for osx.
Installing requirements for osx.
Updating system.....
Installing required packages: llvm35....
Error running 'requirements_osx_brew_libs_install llvm35',
showing last 15 lines of /Users/habovh/.rvm/log/1486028276_rbx-3.7/package_install_llvm35.log
++ case "$1" in
++ [[ -t 1 ]]
++ return 1
++ printf %b 'There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation\n'
There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
++ case "$_system_version" in
++ return 1
Requirements installation failed with status: 1.
```

1486028276_rbx-3.7/package_install_llvm35.log:
```
[2017-02-02 10:37:58] requirements_osx_brew_libs_install
requirements_osx_brew_libs_install () 
{ 
    brew unlink "$@" || true;
    brew install "$@" || { 
        \typeset ret=$?;
        rvm_warn "There were package installation errors, make sure to read the log.

Try \`brew tap --repair\` and make sure \`brew doctor\` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation";
        case "$_system_version" in 
            10.6)
                rvm_warn "
On OSX 10.6 instead of command line tools install:
    https://github.com/downloads/kennethreitz/osx-gcc-installer/GCC-10.6.pkg"
            ;;
        esac;
        return $ret
    }
}
current path: /Users/Jordan/Repositories/Allsquare/rails-app
PATH=/Users/Jordan/.rvm/gems/ruby-2.3.1/bin:/Users/Jordan/.rvm/gems/ruby-2.3.1@global/bin:/Users/Jordan/.rvm/rubies/ruby-2.3.1/bin:/Users/Jordan/.rvm/bin:/Users/Jordan/.nvm/versions/node/v6.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/usr/texbin:/Users/Jordan/.scripts:/usr/local/sbin
command(2): requirements_osx_brew_libs_install llvm35
++ brew unlink llvm35
Error: No such keg: /usr/local/Cellar/llvm35
++ true
++ brew install llvm35
Error: No available formula with the name "llvm35" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
++ typeset ret=1
++ rvm_warn 'There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation'
++ rvm_pretty_print stdout
++ case "${rvm_pretty_print_flag:=auto}" in
++ case "${TERM:-dumb}" in
++ case "$1" in
++ [[ -t 1 ]]
++ return 1
++ printf %b 'There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation\n'
There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
++ case "$_system_version" in
++ return 1
```

**Comment by habovh** [comment]
## Update

It seems that `llvm35` is not supported on macOS Sierra or newer.
We might need to have Rubinius building on more recent version of `llvm`.

**Comment by pkuczynski** [comment]
This has been fixed in #3884. Try with latest RVM (not released yet):

```
rvm get head
rvm install rbx-3.7
```

**Comment by habovh** [comment]
Thank you very much! Despite doing some research I did not encounter the issue you referenced. Sorry about the duplicate!

**Comment by pkuczynski** [comment]
Not a problem at all. Let me know if the issue is fixed...

**Comment by habovh** [comment]
Hey, reporting back after using `rvm get head`. Turns out it does change something but does not actually allow to install Rubinius properly.
The requirements check performed by RVM now successfully passes, however when calling the `./configure`, the command fails with the following output:

```
$ rvm install rbx-3.7
rbx-3.7 - #removing src/rbx-3.7..
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
ruby-2.3.1@rubinius - #regenerating binstubs..........
HEAD is now at 34af1db Bumped rubysl-socket to 2.1.1
Previous HEAD position was 34af1db... Bumped rubysl-socket to 2.1.1
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
From https://github.com/rubinius/rubinius
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
git checkout v3.7
Copying from repo to src path...
ruby-2.3.1@rubinius - #bundle install..
rbx-3.7 - #configuring..
Error running 'env /Users/Jordan/.rvm/wrappers/ruby-2.3.1@rubinius/ruby ./configure --prefix=/Users/Jordan/.rvm/rubies/rbx-3.7 --with-opt-dir=/usr/local/opt/llvm --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl',
showing last 15 lines of /Users/Jordan/.rvm/log/1486116769_rbx-3.7/configure.log
command(9): env /Users/Jordan/.rvm/wrappers/ruby-2.3.1@rubinius/ruby ./configure --prefix=/Users/Jordan/.rvm/rubies/rbx-3.7 --with-opt-dir=/usr/local/opt/llvm --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl
Checking /usr/bin/clang: found
Checking clang++: found
------------------------------ Deprecation notice ------------------------------
Support for compilers other than clang/clang++ is deprecated and will be
removed soon. If your platform does not have support for clang/clang++,
please notify us.
--------------------------------------------------------------------------------

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': Error: No available formula with the name "llvm35" 
not found
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
```

So I'm still unable to build Rubinius on macOS Sierra.
But now I'm afraid the issue comes from Rubinius itself more than RVM. Any idea?

**Comment by habovh** [comment]
@pkuczynski any news on this?

**Comment by pkuczynski** [comment]
It looks like there is some old trash somewhere. Could you list output of:

```
brew list
brew info llvm
```

**Comment by habovh** [comment]
`brew list` output:
```
Jordan@JB-MBP ~ $ brew list
autoconf		imagemagick		python
automake		jpeg			python3
boost			keybase			rclone
cairo			knock			readline
coreutils		lame			redis
czmq			libevent		rsync
eot-utils		libffi			screen
faac			libgpg-error		sdl2
ffmpeg			libksba			sdl2_image
flow			libogg			sqlite
fontconfig		libpng			terminal-notifier
fontforge		libsodium		texi2html
freetype		libtiff			the_silver_searcher
gdbm			libtool			theora
gettext			libvo-aacenc		tmux
git			libvorbis		tree
glew			libvpx			typespeed
glib			libyaml			utf8proc
glm			llvm			watchman
gobject-introspection	makedepend		webp
gource			mysql			x264
hardlink-osx		node			xvid
harfbuzz		openssl			xz
htop-osx		pango			yasm
httpie			pcre			youtube-dl
hydra			pixman			zeromq
icu4c			pkg-config		zlib
```

`brew info llvm` output:
```
Jordan@JB-MBP ~ $ brew info llvm
llvm: stable 3.9.1 (bottled), HEAD [keg-only]
Next-gen compiler infrastructure
http://llvm.org/
/usr/local/Cellar/llvm/3.9.1 (2,089 files, 840.2M)
  Poured from bottle on 2017-01-31 at 10:25:10
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb
==> Dependencies
Build: cmake ✘
Recommended: libffi ✔
Optional: graphviz ✘, ocaml ✘
==> Requirements
Optional: python ✔
==> Options
--universal
	Build a universal binary
--with-graphviz
	Build with graphviz support
--with-lldb
	Build LLDB debugger
--with-ocaml
	Build with ocaml support
--with-python
	Build bindings against custom Python
--with-shared-libs
	Build shared instead of static libraries
--with-toolchain
	Build with Toolchain to facilitate overriding system compiler
--without-compiler-rt
	Do not build Clang runtime support libraries for code sanitizers, builtins, and profiling
--without-libcxx
	Do not build libc++ standard library
--without-libffi
	Do not use libffi to call external functions
--HEAD
	Install HEAD version
==> Caveats
LLVM executables are installed in /usr/local/opt/llvm/bin.
Extra tools are installed in /usr/local/opt/llvm/share/llvm.
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

This formula is keg-only, which means it was not symlinked into /usr/local.

macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/llvm/lib
    CPPFLAGS: -I/usr/local/opt/llvm/include


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/llvm/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/llvm.pth
```

**Comment by pkuczynski** [comment]
Try latest RVM:

```
rvm get master
rvm install rbx-3.7
```

**Comment by habovh** [comment]
@pkuczynski any news? I even tried with the latest version of rvm using `rvm get head`, still no luck.
Were you able to reproduce the issue?

**Comment by pkuczynski** [comment]
@habovh could you please raise a separate issue for building rbx-3.7* on macOS Sierra? You can refer to this issue over there.

You can also attempt another try with some latest changes to master:

```
brew remove llvm
rvm get master
rvm install rbx-3.7
```

This forces linking llvm by brew, so could be helpful in your case.

**Comment by habovh** [comment]
Nope, no luck with that one either. I reopened my issue on Rubinius repository over here:

[macOS and RVM install issue due to llvm35 dependency](https://github.com/rubinius/rubinius/issues/3730)

**Comment by habovh** [comment]
Hi @pkuczynski! Just a quick message over here to warn you that rubinius builds fine one macOS Sierra, both using RVM and without!
The problem was Rubinius' semantic versioning convention. I falsely thought that version `3.7` is the same as `3.70`. However both are very different (in fact, 63 versions separate them!).

And oddly enough, nobody seemed to realise my mistake in trying to install/build a very old RBX version instead of the most recent one.

Here's the issue on RVM's repo: https://github.com/rubinius/rubinius/issues/3730

Thanks for you help and your time!
