### ISSUE TITLE
'scripts/version'  file does not exist

### ISSUE THREAD

**Issue by ShockwaveNN** [rvm/rvm#4072]
## Description

Installing latest RVM from master cause `Could not source '/usr/local/rvm/scripts/version' as file does not exist`

## Steps to reproduce

 1. curl -sSL https://get.rvm.io | bash
 2. source /etc/profile.d/rvm.sh
 3. rvm version

## Expected behavior

Show version of rvm

## Actual behavior

bash: __rvm_version: command not found

## Environment info

```
system:

  system:
    uname:        "Linux ec6eff106145 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "16.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/16.04/x86_64"

  rvm:
    version:      "1.29.1 (master)"
    updated:      "7 minutes 46 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         ""

  environment:
    PATH:         "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by meroku** [comment]
I noticed this happening on my macOS and also ubuntu

**Comment by lwoggardner** [comment]
Looks to be broken by https://github.com/rvm/rvm/commit/cc758aaf4acb44d2a6bfb12547d332047c7b429a

which moved version under functions directory, but did not change function/environments script to look for it there

(I'd send a PR but I don't have an environment)

**Comment by Lax** [comment]
My environment(Docker, debian testing)

```
$ cat Dockerfile 
FROM debian:testing-slim

RUN apt-get update \
	&& apt-get install -q -y --no-install-recommends curl gpg ca-certificates git procps \
	&& rm -rf /var/lib/apt/lists/*

#ENV RVM_INSTALLER https://raw.githubusercontent.com/rvm/rvm/stable/binscripts/rvm-installer
ENV RVM_INSTALLER https://get.rvm.io

RUN \curl -sSL https://get.rvm.io | bash -s stable --ruby
```

I get this error:

```
main: line 880: __rvm_print_headline: command not found
The command '/bin/sh -c \curl -sSL https://get.rvm.io | bash -s stable --ruby' returned a non-zero code: 127
```

**Comment by andymilga** [comment]
@ShockwaveNN 
monkey patch symlink to old location works good:

user installation:
```
ln -s ~/.rvm/scripts/functions/version ~/.rvm/scripts/version
```

**Comment by liangchaob** [comment]
```
ln -s ~/.rvm/scripts/functions/version ~/.rvm/scripts/version
```
still not work in Ubuntu
~$ ln -s ~/.rvm/scripts/functions/version ~/.rvm/scripts/version
~$ rvm -v
/home/alan/.rvm/scripts/cli: line 884: __rvm_version: command not found
```
and could not work well with Capistrano

**Comment by ldm314** [comment]
I am seeing the same issue in CentOS 7. Creating the symlink fixes the warning on login, but rvm -v does not work properly.

**Comment by Sketch** [comment]
Quick fix: Put this into your .bashrc (or shell equivalent)
#!/usr/bin/env bash
__rvm_version()
{
  echo "rvm $(__rvm_version_installed) by $(__rvm_version_authors) [$(__rvm_version_website)]"
}

Working on a patch.

**Comment by xuwaters** [comment]
You can fix it with the following patch.


```
diff --git a/scripts/functions/environment b/scripts/functions/environment
index abd5a147..dd278f74 100644
--- a/scripts/functions/environment
+++ b/scripts/functions/environment
@@ -350,7 +350,7 @@ __rvm_ensure_is_a_function()
 {
   if [[ ${rvm_reload_flag:=0} == 1 ]] || ! is_a_function rvm
   then
-    for script in version functions/selector cd functions/cli cli override_gem
+    for script in functions/version functions/selector cd functions/cli cli override_gem
     do
       if [[ -f "$rvm_scripts_path/$script" ]]
       then
diff --git a/scripts/functions/version b/scripts/functions/version
index 6d12ff71..1fd7ca3b 100755
--- a/scripts/functions/version
+++ b/scripts/functions/version
@@ -30,3 +30,13 @@ __rvm_version_installed()
 {
   echo "$(\command \cat "$rvm_path/VERSION") ($(\command \cat "$rvm_path/RELEASE" 2>/dev/null))"
 }
+
+__rvm_version()
+{
+  __rvm_version_installed
+}
+
+__rvm_remote_version()
+{
+  __rvm_version_remote
+}
```

**Comment by lbias** [comment]
[You have broken version of RVM. Ubuntu does something to RVM that produces lots of errors, the only safe way of fixing for now is to:](https://stackoverflow.com/questions/9056008/installed-ruby-1-9-3-with-rvm-but-command-line-doesnt-show-ruby-v/9056395#9056395). I fixed this problem with this solution.

**Comment by kooogle** [comment]
today i have seen  same  issue
then  i go to path  ~/.rvm/scripts,but there  not file  version excute
I create  a new file  version like  that
```bash
#!/usr/bin/env bash

__rvm_meta()
{
  rvm_meta_author="Wayne E. Seguin"
  rvm_meta_author_email="wayneeseguin@gmail.com"
  rvm_meta_authors=(
    "Wayne E. Seguin <wayneeseguin@gmail.com>"
    "Michal Papis <mpapis@gmail.com>"
  )
  rvm_meta_website="https://rvm.io/"
  rvm_meta_version="${rvm_version}"
}

__rvm_version()
{
  __rvm_meta

  \typeset IFS release
  IFS=':'
  rvm_meta_authors="${rvm_meta_authors[*]}"
  rvm_meta_authors="${rvm_meta_authors//:/, }"

  echo "rvm ${rvm_meta_version} by ${rvm_meta_authors} [${rvm_meta_website}]"
}

```
then  command rvm version running ok

**Comment by onediv** [comment]
i still see issue after fix
/home/qb_app/.rvm/scripts/rvm: line 171: __rvm_version_installed: command not found
/home/qb_app/.rvm/scripts/functions/cli: line 157: __rvm_version_installed: command not found
rvm  by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]

**Comment by praveenpuglia** [comment]
I confirm that this doesn't work in 1.29.2. 

Here's what I get.
```sh
rvm version
rvm:35: command not found: __rvm_version
```

**Comment by neohunter** [comment]
Not working here.

When ssh to server and do rvm version it works, but when using capistrano it raise same error than other:

```
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ec2-user@52.202.109.62: rvm exit status: 127
rvm stdout: Nothing written
rvm stderr: /home/ec2-user/.rvm/scripts/cli: line 884: __rvm_version: command not found

SSHKit::Command::Failed: rvm exit status: 127
rvm stdout: Nothing written
rvm stderr: /home/ec2-user/.rvm/scripts/cli: line 884: __rvm_version: command not found
```

**Comment by ha11o** [comment]
ln -s ~/.rvm/scripts/functions/version ~/.rvm/scripts/version works for me

**Comment by kooogle** [comment]
Hello, sorry for the recent reasons why the work did not log in gmail
mailbox

You encountered this problem I have just met some time ago, and
successfully solved it

Log in to the server to find the directory
Cd ~ / .rvm / scripts

Through the ll command to view all the files, I was found that there is no
version * this executable file

Create a new file via vim version

input content

#!/usr/bin/env bash


__rvm_meta()

{

  rvm_meta_author="Wayne E. Seguin"

  rvm_meta_author_email="wayneeseguin@gmail.com"

  rvm_meta_authors=(

    "Wayne E. Seguin <wayneeseguin@gmail.com>"

    "Michal Papis <mpapis@gmail.com>"

  )

  rvm_meta_website="https://rvm.io/"

  rvm_meta_version="${rvm_version}"

}


__rvm_version()

{

  __rvm_meta


  \typeset IFS release

  IFS=':'

  rvm_meta_authors="${rvm_meta_authors[*]}"

  rvm_meta_authors="${rvm_meta_authors//:/, }"


  echo "rvm ${rvm_meta_version} by ${rvm_meta_authors} [${rvm_meta_website}]
"

}

~

write and quit save file

Authorize the file accordingly

chmod 771 version

2017-08-18 11:22 GMT+08:00 Rajith Jarang <notifications@github.com>:

**Comment by rafaeldso** [comment]
I'm a beginner, and I'm getting this error. How can I apply this path and solve it? Could you pass me the step by step to the solution.

**Comment by kooogle** [comment]
​of course ， I am happy to be able to help you
1、check path  ~/.rvm/scripts there have  version file

2、new file version and chmod 771 version

3、Copy the contents of the attachment,

2017-08-28 23:31 GMT+08:00 Rafael Diego <notifications@github.com>:

**Comment by kooogle** [comment]
Hi，
    Hope this time to let you solve this problem

2017-08-31 9:28 GMT+08:00 Koogle zhang <koogle.zhang@gmail.com>:

**Comment by sachinsreedar92** [comment]
On 2nd step getting the below error:

bash: /etc/profile.d/rvm.sh: No such file or directory
