### ISSUE TITLE
Upgrading RVM Failure

### ISSUE THREAD

**Issue by Twistedben** [rvm/rvm#4442]
Hello, and thanks for help in advance.

A while back when I was upgrading to Rails 5.2 and Ruby 2.5 stable, I was able to eventually get it working but it seems that RVM was broken in the process. I'm currently attempting to upgrade Ruby from 2.5.0 to 2.5.1 and using RVM continually gives me an error. I tried upgrading RVM first, but I get this error below. Not sure what steps to take in an attempt to fix it. I am working in C9 IDE.

>  $ rvm get master
> Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.5.0/bin' is not at first place.
>          Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
>          You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
>          To fix it temporarily in this shell session run: 'rvm use ruby-2.5.0'.
>          To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
> Downloading https://get.rvm.io
> Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
> Verifying /usr/local/rvm/archives/rvm-installer.asc
> gpg: Signature made Sat 31 Mar 2018 09:47:44 PM UTC using RSA key ID BF04FF17
> gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
> gpg:                 aka "Michal Papis <michal.papis@toptal.com>"
> gpg:                 aka "[jpeg image of size 5015]"
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the owner.
> Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
>      Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
> GPG verified '/usr/local/rvm/archives/rvm-installer'
> Downloading https://github.com/rvm/rvm/archive/master.tar.gz
> tar: .github: Cannot utime: Operation not permitted
> tar: binscripts: Cannot utime: Operation not permitted
> tar: config/solaris: Cannot utime: Operation not permitted
> tar: config: Cannot utime: Operation not permitted
> tar: contrib/hudson: Cannot utime: Operation not permitted
> tar: contrib: Cannot utime: Operation not permitted
> tar: docs: Cannot utime: Operation not permitted
> tar: examples: Cannot utime: Operation not permitted
> tar: gem-cache: Cannot utime: Operation not permitted
> tar: gemsets/jruby: Cannot utime: Operation not permitted
> tar: gemsets/ruby/1.8.5: Cannot utime: Operation not permitted
> tar: gemsets/ruby/1.8.6: Cannot utime: Operation not permitted
> tar: gemsets/ruby/1.8.7: Cannot utime: Operation not permitted
> tar: gemsets/ruby: Cannot utime: Operation not permitted
> tar: gemsets: Cannot utime: Operation not permitted
> tar: help/gemset: Cannot utime: Operation not permitted
> tar: help/rvmrc: Cannot utime: Operation not permitted
> tar: help: Cannot utime: Operation not permitted
> tar: hooks: Cannot utime: Operation not permitted
> tar: lib/rvm: Cannot utime: Operation not permitted
> tar: lib: Cannot utime: Operation not permitted
> tar: man/man1: Cannot utime: Operation not permitted
> tar: man: Cannot utime: Operation not permitted
> tar: patches/goruby: Cannot utime: Operation not permitted
> tar: patches/jruby/1.7.9: Cannot utime: Operation not permitted
> tar: patches/jruby: Cannot utime: Operation not permitted
> tar: patches/libxslt-1.1.26: Cannot utime: Operation not permitted
> tar: patches/rbx/2.5.2: Cannot utime: Operation not permitted
> tar: patches/rbx: Cannot utime: Operation not permitted
> tar: patches/readline-5.2: Cannot utime: Operation not permitted
> tar: patches/readline-6.2: Cannot utime: Operation not permitted
> tar: patches/ree/1.8.6: Cannot utime: Operation not permitted
> tar: patches/ree/1.8.7/2010.02: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.4: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.5: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.6: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.7/p72: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.7: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.1/p431: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.1: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.2/head: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.2/p180: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.2/p290: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.2: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p0: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p125: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p194: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p286: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p327: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p362: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p374: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p385: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p429: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/preview1: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3: Cannot utime: Operation not permitted
> tar: patches/ruby/2.0.0/p451: Cannot utime: Operation not permitted
> tar: patches/ruby/2.0.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.2: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.3: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.4: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.5: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.6: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.7: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.8: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.10: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.2: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.3: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.4: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.5: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.6: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.7: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.8: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.9: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.2: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.3: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.4: Cannot utime: Operation not permitted
> tar: patches/ruby/2.4.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.4.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.5.0: Cannot utime: Operation not permitted
> tar: patches/ruby: Cannot utime: Operation not permitted
> tar: patches/tcs: Cannot utime: Operation not permitted
> tar: patchsets/jruby/1.7.9: Cannot utime: Operation not permitted
> tar: patchsets/jruby: Cannot utime: Operation not permitted
> tar: patchsets/rbx/2.5.2: Cannot utime: Operation not permitted
> tar: patchsets/rbx: Cannot utime: Operation not permitted
> tar: patchsets/ree/1.8.6: Cannot utime: Operation not permitted
> tar: patchsets/ree/1.8.7/2012.02: Cannot utime: Operation not permitted
> tar: patchsets/ree/1.8.7: Cannot utime: Operation not permitted
> tar: patchsets/ree: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.6: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p334: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p352: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p357: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p358: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p370: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p371: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p373: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p374: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.1/p431: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/p180: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/p290: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/p318: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/p320: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p125: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p194: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p286: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p327: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p362: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p374: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p385: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p392: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p429: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p448: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p484: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p545: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p547: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p550: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p551: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p195: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p247: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p353: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p451: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p481: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p594: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p598: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p645: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p647: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p648: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.10: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.6: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.7: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.8: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.9: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.10: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.6: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.7: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.8: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.9: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.6: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.7: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.5.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.5.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.5/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby: Cannot utime: Operation not permitted
> tar: patchsets: Cannot utime: Operation not permitted
> tar: rvm-test: Cannot utime: Operation not permitted
> tar: rvm-test-rvm1: Cannot utime: Operation not permitted
> tar: scripts/extras/bash_zsh_support/chpwd: Cannot utime: Operation not permitted
> tar: scripts/extras/bash_zsh_support: Cannot utime: Operation not permitted
> tar: scripts/extras/completion.zsh: Cannot utime: Operation not permitted
> tar: scripts/extras/java_read_properties: Cannot utime: Operation not permitted
> tar: scripts/extras: Cannot utime: Operation not permitted
> tar: scripts/functions/detect_systems: Cannot utime: Operation not permitted
> tar: scripts/functions/hooks: Cannot utime: Operation not permitted
> tar: scripts/functions/manage: Cannot utime: Operation not permitted
> tar: scripts/functions/notes/warnings: Cannot utime: Operation not permitted
> tar: scripts/functions/notes: Cannot utime: Operation not permitted
> tar: scripts/functions/requirements: Cannot utime: Operation not permitted
> tar: scripts/functions: Cannot utime: Operation not permitted
> tar: scripts/zsh/Completion: Cannot utime: Operation not permitted
> tar: scripts/zsh: Cannot utime: Operation not permitted
> tar: scripts: Cannot utime: Operation not permitted
> tar: patches/ree/1.8.7: Cannot utime: Operation not permitted
> tar: patches/ree: Cannot utime: Operation not permitted
> tar: patches: Cannot utime: Operation not permitted
> tar: bin: Cannot utime: Operation not permitted
> tar: Exiting with failure status due to previous errors
> Could not extract RVM sources.
> Downloading https://bitbucket.org/mpapis/rvm/get/master.tar.gz
> tar: .github: Cannot utime: Operation not permitted
> tar: binscripts: Cannot utime: Operation not permitted
> tar: config/solaris: Cannot utime: Operation not permitted
> tar: config: Cannot utime: Operation not permitted
> tar: contrib/hudson: Cannot utime: Operation not permitted
> tar: contrib: Cannot utime: Operation not permitted
> tar: docs: Cannot utime: Operation not permitted
> tar: examples: Cannot utime: Operation not permitted
> tar: gem-cache: Cannot utime: Operation not permitted
> tar: gemsets/jruby: Cannot utime: Operation not permitted
> tar: gemsets/ruby/1.8.5: Cannot utime: Operation not permitted
> tar: gemsets/ruby/1.8.6: Cannot utime: Operation not permitted
> tar: gemsets/ruby/1.8.7: Cannot utime: Operation not permitted
> tar: gemsets/ruby: Cannot utime: Operation not permitted
> tar: gemsets: Cannot utime: Operation not permitted
> tar: help/gemset: Cannot utime: Operation not permitted
> tar: help/rvmrc: Cannot utime: Operation not permitted
> tar: help: Cannot utime: Operation not permitted
> tar: hooks: Cannot utime: Operation not permitted
> tar: lib/rvm: Cannot utime: Operation not permitted
> tar: lib: Cannot utime: Operation not permitted
> tar: man/man1: Cannot utime: Operation not permitted
> tar: man: Cannot utime: Operation not permitted
> tar: patches/goruby: Cannot utime: Operation not permitted
> tar: patches/jruby/1.7.9: Cannot utime: Operation not permitted
> tar: patches/jruby: Cannot utime: Operation not permitted
> tar: patches/libxslt-1.1.26: Cannot utime: Operation not permitted
> tar: patches/rbx/2.5.2: Cannot utime: Operation not permitted
> tar: patches/rbx: Cannot utime: Operation not permitted
> tar: patches/readline-5.2: Cannot utime: Operation not permitted
> tar: patches/readline-6.2: Cannot utime: Operation not permitted
> tar: patches/ree/1.8.6: Cannot utime: Operation not permitted
> tar: patches/ree/1.8.7/2010.02: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.4: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.5: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.6: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.7/p72: Cannot utime: Operation not permitted
> tar: patches/ruby/1.8.7: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.1/p431: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.1: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.2/head: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.2/p180: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.2/p290: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.2: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p0: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p125: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p194: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p286: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p327: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p362: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p374: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p385: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/p429: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3/preview1: Cannot utime: Operation not permitted
> tar: patches/ruby/1.9.3: Cannot utime: Operation not permitted
> tar: patches/ruby/2.0.0/p451: Cannot utime: Operation not permitted
> tar: patches/ruby/2.0.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.2: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.3: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.4: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.5: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.6: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.7: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1.8: Cannot utime: Operation not permitted
> tar: patches/ruby/2.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.10: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.2: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.3: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.4: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.5: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.6: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.7: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.8: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2.9: Cannot utime: Operation not permitted
> tar: patches/ruby/2.2: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.2: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.3: Cannot utime: Operation not permitted
> tar: patches/ruby/2.3.4: Cannot utime: Operation not permitted
> tar: patches/ruby/2.4.0: Cannot utime: Operation not permitted
> tar: patches/ruby/2.4.1: Cannot utime: Operation not permitted
> tar: patches/ruby/2.5.0: Cannot utime: Operation not permitted
> tar: patches/ruby: Cannot utime: Operation not permitted
> tar: patches/tcs: Cannot utime: Operation not permitted
> tar: patchsets/jruby/1.7.9: Cannot utime: Operation not permitted
> tar: patchsets/jruby: Cannot utime: Operation not permitted
> tar: patchsets/rbx/2.5.2: Cannot utime: Operation not permitted
> tar: patchsets/rbx: Cannot utime: Operation not permitted
> tar: patchsets/ree/1.8.6: Cannot utime: Operation not permitted
> tar: patchsets/ree/1.8.7/2012.02: Cannot utime: Operation not permitted
> tar: patchsets/ree/1.8.7: Cannot utime: Operation not permitted
> tar: patchsets/ree: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.6: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p334: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p352: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p357: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p358: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p370: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p371: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p373: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7/p374: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.8.7: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.1/p431: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/p180: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/p290: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/p318: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2/p320: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p125: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p194: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p286: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p327: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p362: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p374: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p385: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p392: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p429: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p448: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p484: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p545: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p547: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p550: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3/p551: Cannot utime: Operation not permitted
> tar: patchsets/ruby/1.9.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p195: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p247: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p353: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p451: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p481: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p594: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p598: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p645: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p647: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0/p648: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.0.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.10: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.6: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.7: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.8: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1.9: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.10: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.6: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.7: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.8: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2.9: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.6: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3.7: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.2: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.3: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.4: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.5.0: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.5.1: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.5/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby/2.5: Cannot utime: Operation not permitted
> tar: patchsets/ruby/head: Cannot utime: Operation not permitted
> tar: patchsets/ruby: Cannot utime: Operation not permitted
> tar: patchsets: Cannot utime: Operation not permitted
> tar: rvm-test: Cannot utime: Operation not permitted
> tar: rvm-test-rvm1: Cannot utime: Operation not permitted
> tar: scripts/extras/bash_zsh_support/chpwd: Cannot utime: Operation not permitted
> tar: scripts/extras/bash_zsh_support: Cannot utime: Operation not permitted
> tar: scripts/extras/completion.zsh: Cannot utime: Operation not permitted
> tar: scripts/extras/java_read_properties: Cannot utime: Operation not permitted
> tar: scripts/extras: Cannot utime: Operation not permitted
> tar: scripts/functions/detect_systems: Cannot utime: Operation not permitted
> tar: scripts/functions/hooks: Cannot utime: Operation not permitted
> tar: scripts/functions/manage: Cannot utime: Operation not permitted
> tar: scripts/functions/notes/warnings: Cannot utime: Operation not permitted
> tar: scripts/functions/notes: Cannot utime: Operation not permitted
> tar: scripts/functions/requirements: Cannot utime: Operation not permitted
> tar: scripts/functions: Cannot utime: Operation not permitted
> tar: scripts/zsh/Completion: Cannot utime: Operation not permitted
> tar: scripts/zsh: Cannot utime: Operation not permitted
> tar: scripts: Cannot utime: Operation not permitted
> tar: patches/ree/1.8.7: Cannot utime: Operation not permitted
> tar: patches/ree: Cannot utime: Operation not permitted
> tar: patches: Cannot utime: Operation not permitted
> tar: bin: Cannot utime: Operation not permitted
> tar: Exiting with failure status due to previous errors
> Could not extract RVM sources.
> Could not update RVM, please report to https://github.com/rvm/rvm/issues

Any help would be appreciated. Thanks!
Ben

**Comment by raelgc** [comment]
@Twistedben Please try run `rvm cleanup all`.

**Comment by BrianHawley** [comment]
@Twistedben this is a known issue. You need to run `rvmsudo rvm cleanup all`. The cleanup operation does a lot of work that doesn't actually make sense in multi-user mode, and the only way to get it to work is to run it in sudo mode.

**Comment by Twistedben** [comment]
THanks a lot, fellas. That worked. I appreciate your time and answers!

**Comment by shadyueh** [comment]
@BrianHawley  Thank you. Your answer solved my problem.

**Comment by jcoulter** [comment]
Fixed mine as well! Thanks!

**Comment by darrell-ulm** [comment]
Worked!

**Comment by Gregory-Colin** [comment]
\curl -sSL https://get.rvm.io | sudo bash -s stable

Worked for me for install/upgrade on WSL (SuSE)

**Comment by MarkMT** [comment]
> @Twistedben this is a known issue. You need to run `rvmsudo rvm cleanup all`. The cleanup operation does a lot of work that doesn't actually make sense in multi-user mode, and the only way to get it to work is to run it in sudo mode. See #4356 and #4361.

Six years have gone by and this is still happening. Did anyone think to put this excellent advice in the documentation? https://rvm.io/rvm/upgrading
